org: canzhen
app: stock-price-crawler
service: ticker-1000-price-crawler
frameworkVersion: '3'

custom:
  tableName: 'stock_price'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs18.x
  timeout: 300
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}'
        - Effect: Allow
          Action:
            - ssm:GetParameters
            - ssm:DescribeParameters
          Resource: '*'
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

# resources:
#   Resources:
#     StockPriceTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: ticker_name
#             AttributeType: S
#         KeySchema:
#           - AttributeName: ticker_name
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:custom.tableName}
